"""Adicionado pedido

Revision ID: 5888f4b056bf
Revises: eee4f309b6bc
Create Date: 2022-03-01 17:52:56.939717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5888f4b056bf'
down_revision = 'eee4f309b6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantdade', sa.Integer(), nullable=True),
    sa.Column('local_entrega', sa.String(), nullable=True),
    sa.Column('tipo_entrega', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='ID_pedido_produto'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='ID_pedido_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Pedidos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Pedidos_id'))

    op.drop_table('Pedidos')
    # ### end Alembic commands ###
